### PR TITLE
Quantlets for Alex Truesdale

### PR DESCRIPTION
**Pull request by alextruesdale**
Please review and merge these Quantlets. Let me know if any updates need to be made.

### CODE REVIEW

**Comment by ghost** [comment]
please, add metainfo.txt

**Comment by alextruesdale** [comment]
Hi,

There are 7 Quantlets here. Each one has a metainfo.txt file. Please let me know if they should be reordered in any way within the repository

1) DEDA_Class_2018WS_Berlin_Property_Analysis/visualisation/gmap_plotter/
2) DEDA_Class_2018WS_Berlin_Property_Analysis/visualisation/growth_plot/
3) DEDA_Class_2018WS_Berlin_Property_Analysis/cleaning/clustering_medical/
4) DEDA_Class_2018WS_Berlin_Property_Analysis/cleaning/clustering_universities/
5) DEDA_Class_2018WS_Berlin_Property_Analysis/analysis/gwr/
6) DEDA_Class_2018WS_Berlin_Property_Analysis/analysis/ols/
7) DEDA_Class_2018WS_Berlin_Property_Analysis/quantlet_scraper/

**Comment by alextruesdale** [comment]
Hold on. I will submit a new pull req.

**Comment by ghost** [comment]
weit, I'll ask Marius first

**Comment by mariussterling** [comment]
Okay! I merged your pull request! 

The names of the Quantlets are 'not correct', they have to be the exact
same thing as written in the metainfo.txt plus the file ending 'py'.
Furthermore the output images can be saved in the same folder, thus the
README.md will contain the images. 

FYI: It was not necessary to change the directory structure. 

Best, 

Marius 

Am 26.02.2019 11:56, schrieb Yegor Klochkov:

> weit, I'll ask Marius first 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 
Student Assistant

International Reasearch Training Group 1792
"High Dimensional Nonstationary Time Series"

School of Business and Economics
Humboldt-Universität zu Berlin
Dorotheenstr. 1
10178 Berlin

E-Mail: Marius.Sterling@hu-berlin.de 

Links:
------
[1]
https://github.com/QuantLet/DEDA_Class_2018WS/pull/2#issuecomment-467393617
[2]

**Comment by mariussterling** [comment]
Hey Alex! 

One more thing! The directories are all called something like
"DEDA_Class_2018WS_Berlin_Property_Analysis_Clustering_Medical"  but the
quantlet name is than called "DEDA_WS201819_clustering_medical", where
the name could be the same, since it is a nice and fancy name. 

Best Marius  

Am 26.02.2019 11:27, schrieb Alex Truesdale:

> Hold on. I will submit a new pull req. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 
Student Assistant

International Reasearch Training Group 1792
"High Dimensional Nonstationary Time Series"

School of Business and Economics
Humboldt-Universität zu Berlin
Dorotheenstr. 1
10178 Berlin

E-Mail: Marius.Sterling@hu-berlin.de 

Links:
------
[1]
https://github.com/QuantLet/DEDA_Class_2018WS/pull/2#issuecomment-467384402
[2]

**Pull request merged**
